name: InstantVoidKill
version: 1.0.0
api: 5.0.0
main: LuthMC\InstantVoidKill\InstantVoidKill
description: Kill players instantly when they fall into the void
author: LuthMC
commands:
  ivk:
    description: InstantVoidKill Command
    usage: "/ivk <set|toggle|settp>"
permission:
  instantvoidkill.use:
    description: Allow use /ivk set command
    default: op
  instantvoidkill.toggle:
    description: Allow use /ivk toggle command
    default: true
  instantvoidkill.settp:
    description: Allow use /ivk settp command
    default: op
